COLUMNS:
  VendorID: int64
  tpep_pickup_datetime: object
  tpep_dropoff_datetime: object
  passenger_count: int64
  RatecodeID: int64
  PULocationID: int64
  DOLocationID: int64
  mean_duration: float64
  mean_distance: float64
  predicted_fare: float64
  generous: int64
  

TARGET_COLUMN:
  name: generous

